# Generated by Django 6.0.7 on 2026-08-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='', upload_to='kids/images')),
            ],
        ),
    ]
