# Generated by Django 6.0.7 on 2026-08-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_remove_contact_id_remove_products_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
