# Generated by Django 6.0.7 on 2026-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_product_p_tagcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boys',
            fields=[
                ('Products_id', models.AutoField(primary_key=True, serialize=False)),
                ('Products_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='', upload_to='kids/images')),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='p_tagcolor',
                ),
                migrations.RemoveField(
                    model_name='product',
                    name='products_tag',
                ),
            ],
        ),
    ]
