# Generated by Django 6.0.7 on 2026-08-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_boys_remove_product_p_tagcolor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boys',
            new_name='Boy',
        ),
    ]
