# Generated by Django 6.0.7 on 2026-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_rename_boys_boy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('Products_id', models.AutoField(primary_key=True, serialize=False)),
                ('Products_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='', upload_to='kids/images')),
            ],
        ),
    ]
