# Generated by Django 6.0.7 on 2026-08-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_girl'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('order', 'Order Status & Delivery'), ('returns', 'Returns & Exchange'), ('product', 'Product Inquiries'), ('general', 'General Support')], default='general', max_length=20),
        ),
    ]
