# Generated by Django 5.2.17 on 2026-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_contact_customer_message_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_view',
            fields=[
                ('Products_id', models.AutoField(primary_key=True, serialize=False)),
                ('Products_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='', upload_to='kids/images')),
            ],
        ),
    ]
